/* Generated By:JavaCC: Do not edit this line. OutputParserConstants.java */
package net.sf.eclipsefp.haskell.hlint.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OutputParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int COLON = 3;
  /** RegularExpression Id. */
  int COLON_SLASH = 4;
  /** RegularExpression Id. */
  int OTHER_CHAR = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\":\"",
    "<COLON_SLASH>",
    "<OTHER_CHAR>",
  };

}
