/* Generated By:JavaCC: Do not edit this line. ProfilingOutputParserConstants.java */
package net.sf.eclipsefp.haskell.profiler.internal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProfilingOutputParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int JOB = 5;
  /** RegularExpression Id. */
  int DATE = 6;
  /** RegularExpression Id. */
  int SAMPLE_UNIT = 7;
  /** RegularExpression Id. */
  int VALUE_UNIT = 8;
  /** RegularExpression Id. */
  int BEGIN_SAMPLE = 9;
  /** RegularExpression Id. */
  int END_SAMPLE = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int INTEGER = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int QUOTEDSTRING = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"JOB\"",
    "\"DATE\"",
    "\"SAMPLE_UNIT\"",
    "\"VALUE_UNIT\"",
    "\"BEGIN_SAMPLE\"",
    "\"END_SAMPLE\"",
    "<DIGIT>",
    "<FLOAT>",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<QUOTEDSTRING>",
  };

}
